"""Complete worked answer models keyed to the original student questions."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parent
E={x['number']:x for x in json.loads((ROOT/'exercises.json').read_text())}
A={};P=[]
def add(n,*items):
    assert len(items)==len(E[n]['questions']),(n,len(items),len(E[n]['questions']))
    A[n]=[{'solution':x[0],'why':x[1]} for x in items]
def answer(n,indices=None,continued=False):
    indices=list(range(len(A[n]))) if indices is None else indices
    s=f'<div class="answer-block" id="ans{n}{"v" if continued else ""}"><h3>Opgave {n} · {E[n]["title"]}{" (vervolg)" if continued else ""}</h3>'
    for i in indices:
        x=A[n][i];s+=f'<p><b>{chr(97+i)}.</b> {x["solution"]}</p><p class="why"><b>Waarom:</b> {x["why"]}</p>'
    return s+'</div>\n\n'
def fig(n,cap):return f'<figure><img src="_assets/{n}.svg" alt="{cap}"><figcaption>{cap}</figcaption></figure>\n\n'
def page(sec,title,body):P.append({'section':sec,'title':title,'body':body})
def table(rows):
    return '<table>'+''.join('<tr>'+''.join(f'<{"th" if i==0 else "td"}>{cell}</{"th" if i==0 else "td"}>' for cell in row)+'</tr>' for i,row in enumerate(rows))+'</table>'
def criteria(t):return '<div class="box small"><b>Beoordelingscriteria bonus</b><br>'+t+'</div>'

# 3.1.1
add(1,('12 − 0,10Q = 4 + 0,10Q → 8 = 0,20Q → Q₀ = <b>40 sleutelhangers per dag</b>. P₀ = 12 − 0,10 × 40 = <b>€ 8 per stuk</b>.','Zonder maatregel ontvangen beide kanten dezelfde prijs; de gewenste hoeveelheden zijn gelijk.'),('P = 4 + 0,10 × 30 = <b>€ 7 per stuk</b>.','Je vult het aantal in de aanbodfunctie in. Dit is nog geen nieuw evenwicht.'))
add(2,('t = Pc − Pp = 9 − 6 = <b>€ 3 per product</b>.','De belasting is het verschil tussen wat de koper betaalt en wat de verkoper na afdracht overhoudt.'),('Nee. Voor de last van kopers heb je Pc − P₀ nodig; voor verkopers P₀ − Pp. <b>P₀ ontbreekt.</b>','De wig geeft de totale belasting, niet de verdeling ten opzichte van de oude prijs.'))
add(3,('Q₀ = 60 en Qt = 40 fruitbekers per dag; P₀ = € 8, Pc = € 10 en Pp = € 6 per beker. <b>Pc en Pp horen beide bij Qt = 40.</b>','Elke verkochte beker heeft een betaald en een na belasting overgehouden bedrag.'),('A + t geeft de benodigde <b>kopersprijs inclusief belasting</b>. Pp lees je op de oorspronkelijke A af: € 6.','Op A + t zit de af te dragen € 4 er al bij.'),('€ 12 gebruiken als Pc geeft Qv = (14 − 12)/0,10 = 20, terwijl bij Pp = 12 − 4 = € 8 het aanbod Qa = (8 − 2)/0,10 = 60 is. Dat is geen evenwicht. De juiste Pc is € 10 bij Q = 40.','De prijs past zich aan via vraag én aanbod; je telt niet zonder meer de belasting op bij P₀.'))
add(4,('Pc = Pp + <b>4</b> = <b>8</b> + 0,10Q.','Verkopers moeten boven op hun gewenste ontvangst de belasting kunnen afdragen.'),('16 − 0,10Q = 8 + 0,10Q → 8 = 0,20Q → Qt = <b>40 posters per week</b>. Pc = 16 − 0,10 × 40 = <b>€ 12</b>; Pp = 4 + 0,10 × 40 = <b>€ 8 per poster</b>.','Gebruik de twee oorspronkelijke functies bij dezelfde nieuwe Q.'),('A + t begint bij € 8 en loopt evenwijdig aan A. Markeer Q = 40, Pc = € 12 en Pp = € 8; zie de oplossingsgrafiek.','De verticale afstand is de belasting per poster.'),('Controle: 12 − 8 = <b>€ 4</b>. De hogere kopersprijs en lagere verkopersontvangst maken dat minder posters worden gevraagd en aangeboden.','Een nieuw snijpunt vervangt het vrije evenwicht.'))
add(5,('18 − 0,20Q = 6 + 0,10Q → 12 = 0,30Q → Q₀ = <b>40 mokken per dag</b>. P₀ = 18 − 0,20 × 40 = <b>€ 10 per mok</b>.','Het vrije evenwicht gebruikt dezelfde prijs voor kopers en verkopers.'),('Nieuw aanbod: Pc = 9 + 0,10Q. 18 − 0,20Q = 9 + 0,10Q → Qt = <b>30 mokken per dag</b>. Pc = 18 − 0,20 × 30 = <b>€ 12</b>; Pp = 6 + 0,10 × 30 = <b>€ 9 per mok</b>.','Pc − Pp = 12 − 9 = € 3; de belasting past precies tussen beide prijzen.'),('A + t start bij € 9. Markeer de twee punten (30; 12) en (30; 9) en de verticale wig. De grafiek hieronder toont de uitwerking.','De belasting verschuift A in kopersprijzen, niet de betalingsbereidheid.'),('Van de € 12 betaling gaat € 3 naar de overheid; de verkoper houdt € 9 over. Eerst betaalde en ontving men € 10.','Een grotere betaling hoeft geen grotere netto-ontvangst voor verkopers te zijn.'))
add(6,('Koper: 9 − 7 = <b>€ 2 meer</b>. Verkoper: 7 − 6 = <b>€ 1 minder</b>. t = 9 − 6 = <b>€ 3 per product</b>.','Beide veranderingen tellen samen op tot de belastingwig.'),('Onjuist. De koper draagt € 2, maar de verkoper draagt nog € 1. De belasting is € 3 per product.','Last voor één groep en totale belasting zijn verschillende grootheden.'))
add(7,('20 − 0,20Q = 2 + 0,10Q → 18 = 0,30Q → Q₀ = <b>60 tassen per dag</b>. P₀ = 20 − 0,20 × 60 = <b>€ 8 per tas</b>.','Zonder belasting zijn vraag en aanbod gelijk bij één prijs.'),('Pc = Pp + 3 = <b>5 + 0,10Q</b>. 20 − 0,20Q = 5 + 0,10Q → 15 = 0,30Q → Qt = <b>50 tassen per dag</b>.','De € 3 wordt aan de aanbodfunctie in kopersprijzen toegevoegd.'),('Pc = 20 − 0,20 × 50 = <b>€ 10</b>. Pp = 2 + 0,10 × 50 = <b>€ 7 per tas</b>. Controle: 10 − 7 = € 3.','De prijzen horen bij dezelfde 50 verkochte tassen.'),('Teken A + t met prijsas-snijding € 5. Markeer (50; 10) op V en (50; 7) op A; verbind de punten verticaal.','Op A + t lees je niet af wat na afdracht voor de verkoper overblijft.'),('Onjuist. De koper betaalt 10 − 8 = <b>€ 2 meer</b>; de verkoper houdt 8 − 7 = <b>€ 1 minder</b> over. De verkoper draagt € 3 af, maar draagt economisch € 1 per tas.','Afdragen is een betalingshandeling; dragen vergelijkt met de oude prijs.'))
add(8,('De uitkomst verandert onder de gegeven voorwaarden niet. Pc − Pp blijft € 4. 16 − 0,10Q = 4 + 0,10Q + 4 → Q = <b>40 producten</b>; Pc = <b>€ 12</b>; Pp = <b>€ 8 per product</b>.','Kopers reageren op hun totale betaling; verkopers op hun ontvangst. De belastingwig is gelijk gebleven.'),('Geldstroom: <b>koper → verkoper: € 8</b>; <b>koper → overheid: € 4</b>. De koper betaalt samen € 12. Verkopers ontvangen € 8.','Hetzelfde totale belastingbedrag kan langs een andere betalingsroute lopen.'))
add(9,('%ΔP = (12 − 10)/10 × 100% = <b>+20%</b>. %ΔQv = (180 − 200)/200 × 100% = <b>−10%</b>.','De oude waarden zijn de basis; een daling krijgt een minteken.'),('Ev = −10% / +20% = <b>−0,5</b>. |Ev| = 0,5 &lt; 1: <b>prijsinelastisch</b>.','De hoeveelheid verandert procentueel minder sterk dan de prijs.'))

# 3.1.2
add(10,('CS = ½ × 40 × (18 − 10) = <b>€ 160</b>. PS = ½ × 40 × (10 − 6) = <b>€ 80</b>. Basis: 40 producten; hoogten: € 8 en € 4 per product.','Het product van aantal en euro per product geeft euro, niet euro per product.'))
add(11,('W = 500 − 470 = <b>€ 30</b>. De € 120 is een overheidsontvangst, geen volledig verdwenen voordeel.','Een geldstroom is niet hetzelfde als het verlies aan gezamenlijke voordelen van handel.'))
add(12,('CS ligt boven Pc = € 10 en onder V; PS onder Pp = € 6 en boven A. O is de rechthoek tussen € 6 en € 10 tot Q = 40; W ligt tussen Q = 40 en Q = 60.','Elke oppervlakte heeft een eigen economische betekenis.'),('O = 40 × 4 = <b>€ 160 per dag</b>. W = ½ × (60 − 40) × 4 = <b>€ 40 per dag</b>.','O gebruikt verkochte eenheden; W gebruikt de gemiste eenheden.'),('Tussen Pc en Pp zit boven de verkochte hoeveelheid de belastingopbrengst. Alleen de driehoek van weggevallen voordelige transacties is W.','De overheid ontvangt geld over handel die nog wel plaatsvindt.'))
ledger=table([['Grootheid (€ per dag)','Zonder','Met'],['CS','½ × 60 × (16 − 10) = 180','½ × 40 × (16 − 12) = 80'],['PS','½ × 60 × (10 − 4) = 180','½ × 40 × (8 − 4) = 80'],['O','0','4 × 40 = 160'],['CS + PS + O','360','320']])
add(13,(ledger,'De verkochte hoeveelheid is de basis van de driehoeken; de relevante prijs bepaalt de hoogte.'),('O = <b>€ 160 per dag</b>. W = 360 − 320 = <b>€ 40 per dag</b>. Controle: ½ × (60 − 40) × 4 = € 40.','Het verlies aan CS en PS is € 200, maar daarvan ontvangt de overheid € 160.'),('Onjuist. € 2 koperslast + € 2 verkoperslast = <b>€ 4 belasting per set</b>. De overheid ontvangt de hele € 4 bij iedere verkoop.','De verdeling van de last verandert niet het bedrag dat wordt afgedragen.'))
add(14,('Koperslast = 12 − 10 = <b>€ 2</b>; verkoperslast = 10 − 8 = <b>€ 2 per pakket</b>. Afwenteling = 2/4 × 100% = <b>50%</b>.','Beide lasten worden met de oude prijs vergeleken.'),('Oud: CS = ½ × 60 × 6 = € 180 en PS = ½ × 60 × 6 = € 180. Nieuw: CS = ½ × 40 × 4 = € 80 en PS = ½ × 40 × 4 = € 80. O = 4 × 40 = € 160. W = 360 − (80 + 80 + 160) = <b>€ 40 per week</b>.','De belastingopbrengst blijft onderdeel van de welvaartsmaat.'),('Markeer Qt = 40, Pc = € 12 en Pp = € 8. O is een rechthoek met breedte 40 en hoogte € 4. W heeft basis 20 en hoogte € 4.','Je arceert de budgetoverdracht en de gemiste transacties verschillend.'))
add(15,('In <b>markt Y</b>. Kopers kunnen daar minder makkelijk op een hogere prijs reageren. Bij gelijk aanbod kan een groter deel via de prijs bij hen terechtkomen.','De minder prijsgevoelige kant draagt relatief meer last.'),('De afdrachtregel is in beide markten dezelfde en zegt niet hoe prijzen veranderen.','Economische belastingdruk volgt uit de aanpassing van beide kanten van de markt.'))
add(16,('Koper: 10 − 8 = <b>€ 2 per tas</b>. Verkoper: 8 − 7 = <b>€ 1 per tas</b>. Afwenteling = 2/3 × 100% = <b>66,67%</b>.','Samen dragen beide kanten € 3 per verkochte tas.'),('O = t × Qt = 3 × 50 = <b>€ 150 per dag</b>.','De belasting wordt over de 50 daadwerkelijke verkopen geheven.'),('Oud: CS = ½ × 60 × (20 − 8) = € 360; PS = ½ × 60 × (8 − 2) = € 180. Nieuw: CS = ½ × 50 × (20 − 10) = € 250; PS = ½ × 50 × (7 − 2) = € 125.<br>Nieuwe maat = 250 + 125 + 150 = <b>€ 525</b>. W = (360 + 180) − 525 = <b>€ 15 per dag</b>.','Verlies aan privaat surplus is deels een overdracht naar de overheid.'),('Zie de grafiek. O ligt tussen € 7 en € 10 tot Q = 50. W ligt tussen Q = 50 en Q = 60: basis 10 tassen, hoogte € 3 per tas. ½ × 10 × 3 = € 15.','De basis van W is niet Qt maar de afname van de hoeveelheid.'),('Onjuist. Bij gelijk aanbod en dezelfde belasting leidt minder prijsgevoelige vraag juist tot een groter aandeel voor kopers.','Wie minder makkelijk kan afzien van aankoop, kan de last minder makkelijk ontwijken.'))
add(17,('A: 9 = 14 − 0,10Q → Q = <b>50</b>, een daling van 10. B: 9 = 20 − 0,20Q → Q = <b>55</b>, een daling van 5. Bij dezelfde beginwaarden en prijsstijging reageert <b>B minder sterk</b>.','Met gelijke beginprijzen en hoeveelheden kun je de reacties hier zinvol vergelijken.'),('A: koper 9,50 − 8 = € 1,50 en verkoper 8 − 6,50 = € 1,50: elk 50%. B: koper € 2 en verkoper € 1: 66,67% en 33,33%. Minder reactie van de vraag in B past bij een groter kopersaandeel.','Het aanbod, de belasting en de uitgangswaarden zijn gelijk. Een schaalverschil tussen willekeurige grafieken kan deze vergelijking niet verklaren.'))
add(18,('TO = 9 × 100 = <b>€ 900 per dag</b>. TK = 300 + 4 × 100 = <b>€ 700 per dag</b>. Winst = 900 − 700 = <b>€ 200 per dag</b>.','Van de opbrengst moeten nog de totale kosten af.'),('€ 9 is de ontvangst per verkocht product, niet wat er na alle kosten overblijft. Hier zijn de gemiddelde totale kosten 700/100 = € 7; de gemiddelde winst is € 2.','Opbrengst en winst zijn niet uitwisselbaar.'))

# 3.1.3
add(19,('Belasting: Pp = Pc − t = 11 − 3 = <b>€ 8</b>. Subsidie: Pp = Pc + s = 11 + 3 = <b>€ 14 per product</b>.','Belasting wordt afgedragen uit de betaling; subsidie komt erbovenop.'))
add(20,('U = s × Qsub = 2 × 60 = <b>€ 120 per week</b>. Niet 2 × 10 = € 20.','Volgens de regeling krijgt elke verkochte plaats subsidie, ook een plaats die zonder subsidie zou zijn verkocht.'))
add(21,('Pc = <b>€ 10</b> en Pp = <b>€ 14 per plaats</b>. De aanbieder ontvangt € 10 van de koper plus € 4 van de gemeente.','Pp is de totale ontvangst vóór productiekosten.'),('Voor dezelfde gewenste totale ontvangst van de aanbieder hoeft de koper € 4 minder te betalen. Daarom verschuift A in kopersprijzen omlaag.','Er is geen verandering in wat kopers voor het product willen betalen.'),('Koper: 12 − 10 = <b>€ 2 voordeel</b>. Aanbieder: 14 − 12 = <b>€ 2 voordeel per plaats</b>.','De subsidie wordt uitbetaald aan aanbieders, maar beide kanten profiteren via de prijzen.'))
add(22,('Pc = Pp − <b>4</b> = <b>6</b> + 0,10Q. 22 − 0,10Q = 6 + 0,10Q → Qsub = <b>80 lesplaatsen per week</b>. Pc = 22 − 0,10 × 80 = <b>€ 14</b>; Pp = 10 + 0,10 × 80 = <b>€ 18 per plaats</b>.','Pp − Pc = 4; het aanbod in kopersprijzen is verlaagd.'),('A − s begint bij € 6. Markeer Q = 80 met de punten (80; 14) en (80; 18); zie de grafiek.','De lagere lijn hoort bij de kopersprijs, de oorspronkelijke A bij de totale ontvangst.'),('U = 4 × 80 = € 320. CS = ½ × 80 × (22 − 14) = € 320. PS = ½ × 80 × (18 − 10) = € 320. Netto: 320 + 320 − 320 = <b>€ 320 per week</b>. Daling ten opzichte van € 360: <b>€ 40</b>.','De subsidie-uitgaven moeten worden afgetrokken.'))
add(23,('Nieuw aanbod: Pc = 3 + 0,10Q. 24 − 0,20Q = 3 + 0,10Q → Qsub = <b>70 plaatsen per week</b>. Pc = 24 − 0,20 × 70 = <b>€ 10</b>. Pp = 6 + 0,10 × 70 = <b>€ 13</b>. Markeer deze punten in de grafiek.','De wig van € 3 vergroot de hoeveelheid ten opzichte van 60.'),('U = 3 × 70 = <b>€ 210</b>. CS = ½ × 70 × (24 − 10) = <b>€ 490</b>. PS = ½ × 70 × (13 − 6) = <b>€ 245 per week</b>.','De nieuwe verkochte hoeveelheid is de basis; beide kanten gebruiken hun eigen prijs.'),('CS + PS − U = 490 + 245 − 210 = <b>€ 525 per week</b>. W = 540 − 525 = <b>€ 15 per week</b>. Er zijn geen baten voor buitenstaanders meegeteld.','Zonder zulke baten kosten de extra transacties voorbij het vrije evenwicht meer dan hun betalingsbereidheid.'))
add(24,('s = <b>€ 2 + € 1 = € 3 per product</b>.','De daling van Pc en de stijging van Pp tellen samen op tot de subsidie.'),('De overheid ontbreekt: zij betaalt <b>€ 3 per verkochte eenheid</b>. Je kunt daarom niet uit alleen de voordelen voor kopers en verkopers concluderen dat iedereen profiteert.','Het subsidievoordeel wordt met publieke middelen betaald.'))
add(25,('Pc = Pp − 3 = <b>5 + 0,10Q</b>. 26 − 0,20Q = 5 + 0,10Q → 21 = 0,30Q → Qsub = <b>70 plaatsen per week</b>. Pc = 26 − 0,20 × 70 = <b>€ 12</b>; Pp = 8 + 0,10 × 70 = <b>€ 15 per plaats</b>.','Controle: 15 − 12 = € 3.'),('U = 3 × 70 = <b>€ 210 per week</b>.','De subsidie geldt voor alle verkochte cursusplaatsen.'),('Kopersvoordeel: 14 − 12 = <b>€ 2</b>. Aanbiedersvoordeel: 15 − 14 = <b>€ 1 per plaats</b>.','Via de lagere kopersprijs ontvangen ook kopers een deel van het voordeel.'),('CS = ½ × 70 × (26 − 12) = <b>€ 490</b>. PS = ½ × 70 × (15 − 8) = <b>€ 245</b>. Netto = 490 + 245 − 210 = <b>€ 525</b>. W = 540 − 525 = <b>€ 15 per week</b>.','CS en PS groeien samen met € 195, maar de overheid betaalt € 210.'),('Markeer Q = 70, Pc = € 12 en Pp = € 15. De uitgavenrechthoek heeft breedte 70 en hoogte € 3. De claim is onjuist: de welvaartsmaat daalt hier € 15.','De oefening veronderstelt geen baten voor buitenstaanders die dit verlies zouden compenseren.'))
add(26,('A: U = 3 × 70 = <b>€ 210</b>. B: gegeven vaste steun = <b>€ 210</b>. Alleen A geeft bij een extra verkoop opnieuw € 3. Bij B blijven volgens de bron de marginale voorwaarden en het vrije evenwicht gelijk.','Gelijke totale uitgaven betekenen niet gelijke prikkels per extra product.'),('Onder B volgt geen extra vergoeding uit een extra verkochte plaats. Je kunt daarom het aanbod in kopersprijzen niet met € 3 verlagen.','Een vast totaalbedrag is geen subsidie per verkochte eenheid; de bron sluit veranderingen in marginale kosten en deelname bovendien expliciet uit.'))
add(27,('GCK bij Q = 100: 600/100 = <b>€ 6 per stoel</b>. Bij Q = 150: 600/150 = <b>€ 4 per stoel</b>.','Dezelfde vaste kosten worden over meer verhuurde stoelen verdeeld.'),('TCK blijft € 600 per week. Alleen het bedrag per verhuurde stoel daalt.','De productiecapaciteit en het totale vaste kostenbedrag veranderen niet.'))

# 3.1.4
add(28,('18 − 0,20Q = 6 + 0,10Q → Q₀ = <b>40 producten per dag</b>. P₀ = 18 − 0,20 × 40 = <b>€ 10 per product</b>.','In het vrije evenwicht zijn gewenste aankopen en verkopen gelijk.'),('Vraag: 8 = 18 − 0,20Qv → Qv = <b>50</b>. Aanbod: 8 = 6 + 0,10Qa → Qa = <b>20 producten per dag</b>.','Bij een gegeven prijs hoeven vraag en aanbod niet gelijk te zijn.'))
add(29,('Nee. P = <b>€ 12</b> blijft toegestaan, want € 12 ligt onder het maximum van € 15.','Een maximumprijs is een bovengrens, geen verplicht te vragen prijs.'))
add(30,('Qv = <b>80</b>; Qa = <b>40 puzzels per week</b>. Werkelijk verkocht: <b>40</b>.','Er is geen extra aanvoer en alle aangeboden puzzels worden verkocht.'),('Het tekort loopt horizontaal van Q = 40 tot Q = 80 en is 40 puzzels. Het is geen bedrag per puzzel.','Een tekort meet een verschil tussen aantallen, niet tussen prijzen.'),('Onjuist. Er worden 40 puzzels verkocht; 40 van de 80 vragers krijgen geen product.','Een lagere toegestane prijs helpt niet iedere geïnteresseerde koper als het product ontbreekt.'))
add(31,('Pmax = € 8 ligt onder P₀ = € 10: <b>bindend</b>.','De vrije evenwichtsprijs is niet toegestaan.'),('8 = 16 − 0,10Qv → Qv = <b>80</b>. 8 = 4 + 0,10Qa → Qa = <b>40</b>. Verkoop = <b>40 pakketten per week</b>; tekort = 80 − 40 = <b>40 pakketten per week</b>.','Alle aangeboden pakketten worden verkocht, maar niet alle gewenste aankopen kunnen doorgaan.'),('Teken Pmax = € 8. De snijpunten zijn (40; 8) op A en (80; 8) op V. Markeer het horizontale tekort.','Beide hoeveelheden horen bij één en dezelfde verkoopprijs.'),('Bij een maximum van € 12 blijft <b>P = € 10 en Q = 60</b>.','Het vrije evenwicht ligt onder de bovengrens en blijft dus toegestaan.'))
add(32,('20 − 0,20Q = 2 + 0,10Q → Q₀ = <b>60</b>. P₀ = 20 − 0,20 × 60 = <b>€ 8</b>. Het maximum € 6 bindt.','€ 6 is lager dan de vrije evenwichtsprijs.'),('6 = 20 − 0,20Qv → Qv = <b>70</b>. 6 = 2 + 0,10Qa → Qa = <b>40</b>. Verkoop = <b>40 spellen per week</b>; tekort = <b>30 spellen per week</b>.','Zonder extra aanvoer kunnen niet alle 70 vragers kopen.'),('Markeer Pmax = € 6, Qa = 40 als verkoop, Qv = 70 als gewenste aankoop en het tekort van 30.','De aangeboden hoeveelheid bepaalt hier de werkelijke verkopen.'),('Je weet dat 40 spellen worden verkocht, maar niet <b>aan welke 40 vragers</b>. Daarvoor is een toewijzingsregel nodig.','Een loting of andere selectie kan andere kopers een product geven.'))
add(33,('Alleen de lagere grens bij de oude markt: € 9 &gt; € 8, dus <b>niet bindend</b>.','De oude vrije prijs blijft toegestaan.'),('Bij de nieuwe markt: € 9 &lt; € 12, dus <b>wel bindend</b>. De uitspraak is onjuist: je moet de grens met het toepasselijke vrije evenwicht vergelijken.','Niet alleen de regeling, maar ook de marktomstandigheden bepalen of zij effect heeft.'))
add(34,('18 − 0,10Q = 6 + 0,10Q → 12 = 0,20Q → Q₀ = <b>60 tenten per weekend</b>. P₀ = 18 − 0,10 × 60 = <b>€ 12 per tent</b>. Pmax = € 10 bindt.','De vrije huur van € 12 wordt verboden.'),('10 = 18 − 0,10Qv → Qv = <b>80</b>. 10 = 6 + 0,10Qa → Qa = <b>40</b>. Werkelijk verhuurd: <b>40 tenten</b>. Tekort: 80 − 40 = <b>40 tenten per weekend</b>.','Er is geen extra aanvoer; alle 40 aangeboden tenten worden verhuurd.'),('Markeer de horizontale lijn Pmax = € 10, Qa = 40 en Qv = 80. Label 40 als werkelijke verhuringen en 40–80 als tekort.','Vraag, aanbod en werkelijk verhuurde aantallen hebben verschillende betekenissen.'),('Onjuist. Van de 80 vragers krijgen alleen de 40 hoogste betalingsbereidheden een tent. De overige 40 vragers die € 10 willen betalen, krijgen er geen.','Een lagere huur maakt toegang niet voor iedereen mogelijk.'),('Bij Pmax = € 14 blijft de werkelijke huur <b>€ 12</b> en worden <b>60 tenten per weekend</b> verhuurd.','Het maximum is hoger dan de vrije huur en bindt niet.'))
add(35,('A: (12 − 6) + (10 − 6) = <b>€ 10 CS</b>. B: (8 − 6) + (7 − 6) = <b>€ 3 CS</b>. Niet-kopers leveren in deze berekening geen CS.','Alleen bij een daadwerkelijke aankoop tel je betalingsbereidheid minus prijs mee.'),('In beide situaties zijn prijs (€ 6) en aantal (2) gelijk, maar kopen andere mensen met andere betalingsbereidheden.','De toewijzing bepaalt welke individuele voordelen worden opgeteld.'),('Nee. A heeft in deze berekening meer CS, maar “eerlijk” vraagt een afzonderlijk criterium, bijvoorbeeld gelijke kansen.','Een efficiëntiemaat is niet hetzelfde als een verdelingsnorm.'))
add(36,('30 − 0,50Q = 6 + 0,25Q → 24 = 0,75Q → Q₀ = <b>32 kaartjes</b>. P₀ = 30 − 0,50 × 32 = <b>€ 14 per kaartje</b>.','Er is geen prijsregel en de oorspronkelijke lijnen bepalen het evenwicht.'),('CS = ½ × 32 × (30 − 14) = <b>€ 256</b>. PS = ½ × 32 × (14 − 6) = <b>€ 128</b>.','De oppervlakten meten de voordelen bij de 32 verhandelde kaartjes.'))

# 3.1.5
add(37,('100 − 5P = 5P − 20 → 120 = 10P → P₀ = <b>€ 12</b>. Q₀ = 100 − 5 × 12 = <b>40 kratten per week</b>. Bij P = € 14: Qv = 100 − 70 = 30; Qa = 70 − 20 = 50. Aanbodoverschot = 50 − 30 = <b>20 kratten per week</b>.','Het overschot is aangeboden hoeveelheid minus particuliere vraag.'))
add(38,('<b>€ 12</b>. Deze prijs is hoger dan de ondergrens van € 9 en blijft toegestaan.','Een minimumprijs verplicht de markt niet om naar die ondergrens te dalen.'))
add(39,('Particulieren kopen <b>40 kratten</b>. Er worden <b>80 kratten</b> aangeboden. De overheid koopt het verschil: <b>40 kratten per week</b>.','De bron garandeert volledige opkoop van het overschot.'),('U = 10 × (80 − 40) = <b>€ 400 per week</b>. De overheid koopt niet de 40 kratten die particulieren al afnemen.','Het budget wordt over de publieke aankopen berekend, niet over alle productie.'),('De <b>40 kratten aanbodoverschot</b> zijn dan niet automatisch verkocht; er blijven alleen 40 particuliere aankopen.','Een minimumprijs zonder opkoopgarantie creëert geen extra afnemer.'))
add(40,('14 = 18 − 0,10Qv → Qv = <b>40</b>. 14 = 6 + 0,10Qa → Qa = <b>80</b>. Overscho t = 80 − 40 = <b>40 kratten per week</b>.'.replace('Overscho t','Overschot'),'Kopers reageren op de hogere prijs door minder te vragen; verkopers door meer aan te bieden.'),('Teken Pmin = € 14; de snijpunten geven Qv = 40 en Qa = 80. U = 14 × 40 = <b>€ 560 per week</b>. De rechthoek loopt van Q = 40 tot 80 en van P = 0 tot 14.','Alleen de overheid koopt dit aanbodoverschot.'),('Bij alleen quotum 40: P = 18 − 0,10 × 40 = <b>€ 14</b>; particulieren kopen <b>40 kratten</b>; U = <b>€ 0</b>.','Het quotum vervangt de hele prijs- en opkoopregeling; de overheid koopt niet langer mee.'))
add(41,('22 − 0,10Q = 10 + 0,10Q → Q₀ = <b>60</b>, P₀ = <b>€ 16</b>. Bij Pmin = € 18: Qv = (22 − 18)/0,10 = <b>40</b>; Qa = (18 − 10)/0,10 = <b>80</b>; aanbodoverschot = <b>40 kratten per week</b>.','De minimumprijs ligt boven het vrije evenwicht.'),('Telers verkopen samen <b>80 kratten</b>: 40 aan particulieren en 40 aan de overheid. U = 18 × 40 = <b>€ 720 per week</b>. Zie de rechthoek in de grafiek.','De garantie maakt alle aangeboden productie verkoopbaar.'),('Quotum 40: P = 22 − 0,10 × 40 = <b>€ 18</b>. Productie is <b>40 in plaats van 80 kratten per week</b>.','Eenzelfde prijs kan samengaan met een andere hoeveelheid productie en andere publieke uitgaven.'))
add(42,('Zonder opkoop of andere afnemers wordt <b>30</b> verkocht. Aanbodoverschot = 70 − 30 = <b>40 producten</b>.','Aangeboden producten zijn niet automatisch verkochte producten.'),('Een minimumprijs noemt nog geen overheidsaankopen. Gratis quota leveren geen veilingopbrengst op. Je mag dus geen positieve budgetbetaling uit deze gegevens verzinnen.','Voor een budgetberekening is een expliciete betaling, aankoop of ontvangstenregel nodig.'))
add(43,('20 − 0,10Q = 8 + 0,10Q → 12 = 0,20Q → Q₀ = <b>60 kratten per week</b>. P₀ = 20 − 0,10 × 60 = <b>€ 14</b>. De minimumprijs van € 16 bindt.','De vrije prijs is lager dan de nieuwe ondergrens.'),('16 = 20 − 0,10Qv → Qv = <b>40</b>. 16 = 8 + 0,10Qa → Qa = <b>80</b>. Overschot = <b>40 kratten</b>. Dankzij opkoop verkopen telers samen <b>80 kratten per week</b>.','De overheid neemt de 40 kratten af die particulieren niet kopen.'),('Overheidsaankopen = 80 − 40 = <b>40 kratten</b>. U = 16 × 40 = <b>€ 640 per week</b>. De rechthoek is 40 kratten breed en € 16 per krat hoog.','Je gebruikt het overheidsgedeelte van de afzet, niet de hele productie.'),('Quotum 40 bindt, want het ligt onder 60. P = 20 − 0,10 × 40 = <b>€ 16 per krat</b>. Productie = <b>40 kratten</b>; U = <b>€ 0 per week</b>.','Regeling B vervangt A; gratis rechten en geen opkoop geven hier geen budgetbetaling.'),('Onjuist. De prijs is wel in beide gevallen € 16, maar de productie is <b>80 tegenover 40 kratten</b> en U is <b>€ 640 tegenover € 0</b>.','Een overeenkomst in prijs bewijst niet dat de mechanismen en gevolgen gelijk zijn.'))
add(44,('De € 640 is een betaling voor goederen. Dat is niet automatisch € 640 aan verloren welvaart. Voor een oordeel zijn ook de reële kosten en de waarde van het gebruik van de goederen van belang; die zijn hier niet voldoende gegeven.','Een budgetbedrag alleen meet geen nettoverlies aan gezamenlijke voordelen.'),('Bijvoorbeeld: <b>wat gebeurt er met de kratten en welke waarde heeft dat gebruik?</b> En: <b>welke opslag-, vervoer- of vernietigingskosten ontstaan?</b> Andere relevante, duidelijk uitgelegde informatie is ook goed.','De bron geeft de betaling, niet de volledige maatschappelijke baten en kosten.'))
add(45,('%ΔP = (10 − 8)/8 × 100% = <b>+25%</b>. %ΔQv = (70 − 80)/80 × 100% = <b>−12,5%</b>. Ev = −12,5%/25% = <b>−0,5</b>: prijsinelastisch.','Gebruik het minteken voor de richting en |Ev| voor de sterkte.'),('TO oud = 8 × 80 = <b>€ 640 per week</b>. TO nieuw = 10 × 70 = <b>€ 700 per week</b>. De omzet stijgt € 60, maar kostengegevens ontbreken voor een winstvergelijking.','Winst hangt van TO én TK af.'))

# 3.1.6
add(46,('<b>Belasting per verkocht product</b>. Pc is hoger dan Pp.','Een deel van de kopersbetaling gaat naar de overheid.'),('<b>Subsidie per verkochte plaats</b>. Bereken U over alle daadwerkelijk verkochte, subsidiabele plaatsen.','Een vergoeding per verkoop is niet beperkt tot de extra verkoop.'),('<b>Maximumprijs</b>. € 7 &lt; € 9, dus bindend. Bereken Qv, Qa, verkopen en tekort bij € 7.','De prijsregel verplaatst geen oorspronkelijke vraag- of aanbodlijn.'),('<b>Bindend productiequotum</b>. De 50 toegestane producten worden geprijsd via de vraaglijn V.','De hoeveelheid is begrensd, niet rechtstreeks de prijs.'))
add(47,('Verkoop = <b>30</b>; aanbodoverschot = 70 − 30 = <b>40 producten</b>; U = <b>€ 0</b>.','Zonder andere afnemer blijven alleen de particuliere aankopen over.'),('De overheid koopt <b>40 producten</b>. U = 12 × 40 = <b>€ 480</b>.','De nieuwe aankoopgarantie maakt het aanbodoverschot afzetbaar.'),('De prijsregel is hetzelfde, maar nu is er een extra afnemer met een expliciete betalingsbelofte.','Het gevolg van een minimumprijs hangt ook van de aankoopregel af.'))
add(48,('A is een belasting per product; B een maximumprijs. Vrij evenwicht: 24 − 0,20Q = 6 + 0,10Q → 18 = 0,30Q → Q₀ = <b>60 bandjes per dag</b>. P₀ = 24 − 0,20 × 60 = <b>€ 12 per bandje</b>.','Eerst identificeer je het mechanisme; daarna kies je de rekenroute.'),('Bij A: Pc = 9 + 0,10Q. 24 − 0,20Q = 9 + 0,10Q → Qt = <b>50</b>. Pc = 24 − 0,20 × 50 = <b>€ 14</b>; Pp = 6 + 0,10 × 50 = <b>€ 11</b>. Koperslast = 14 − 12 = <b>€ 2</b>; verkoperslast = 12 − 11 = <b>€ 1 per bandje</b>.','Pc − Pp is precies de belasting van € 3.'),('O = 3 × 50 = <b>€ 150 per dag</b>. CS = ½ × 50 × (24 − 14) = <b>€ 250</b>. PS = ½ × 50 × (11 − 6) = <b>€ 125</b>. Nieuwe welvaartsmaat = 250 + 125 + 150 = <b>€ 525</b>. Oud = 360 + 180 = € 540. W = 540 − 525 = <b>€ 15 per dag</b>.','Overheidsontvangsten tellen mee in de maat; ze zijn geen verdwenen geld.'),('Qt = 50; Pc = € 14; Pp = € 11. O is de rechthoek van Q = 0 tot 50 tussen P = 11 en 14. W ligt tussen Q = 50 en Q = 60: ½ × 10 × 3 = € 15.','O gebruikt de overblijvende verkopen; W de gemiste voordelige transacties.'),('Bij B bindt € 10, want het ligt onder € 12. 10 = 24 − 0,20Qv → Qv = <b>70</b>. 10 = 6 + 0,10Qa → Qa = <b>40</b>. Verkopen = <b>40</b>; tekort = 70 − 40 = <b>30 bandjes per dag</b>.','Geen extra aanvoer betekent dat niet alle vragers kunnen kopen.'),('Beide delen zijn onjuist. Bij B willen 70 mensen een bandje, maar er worden 40 verkocht: 30 vragers krijgen er geen. Bij A ontvangt de overheid € 150, terwijl W € 15 is.<br>Een onderbouwd verschil: kopers die onder B kunnen kopen betalen € 10 in plaats van € 14 onder A, maar er worden ook 40 in plaats van 50 bandjes verkocht. Er volgt hier geen volledige welvaartsrangschikking van beide plannen.','Een conclusie benoemt zowel prijs als toegang en onderscheidt een overdracht van een verlies.'))

# Explicit pages; target source and answer figures can be independently inspected.
page('3.1','Antwoorden','''<div class="kicker">4VECO · ECONOMIE · 4 VWO · BOEK 3</div>
# Antwoorden<br>Overheidsingrijpen

Dit antwoordboek hoort bij het leerlinghoofdstuk van 40 pagina’s. Het bevat de uitwerkingen van alle 48 opgaven. De vijf uitgewerkte voorbeelden staan in het leerlinghoofdstuk zelf.

<div class="box"><b>Gebruik bij het nakijken</b><br>Vergelijk niet alleen het eindgetal. Controleer welke prijs en hoeveelheid zijn gebruikt, welke partij betaalt en waarom een oppervlakte iets over surplus of het overheidsbudget zegt.</div>

| Paragraaf | Opgaven | Uitwerkingen vanaf |
|---|---|---:|
| 3.1.1 Belastingen | 1–9 | 2 |
| 3.1.2 Belastingdruk en welvaartsverlies | 10–18 | 6 |
| 3.1.3 Subsidies | 19–27 | 10 |
| 3.1.4 Maximumprijs | 28–36 | 14 |
| 3.1.5 Minimumprijs en quota | 37–45 | 18 |
| 3.1.6 Gemengde opgaven | 46–48 | 22 |

### Notatie en afronding

Pc = de kopersprijs. Pp = de verkopersontvangst na belasting of inclusief subsidie, maar vóór productiekosten. Qt en Qsub zijn de verkochte hoeveelheden mét belasting of subsidie; Qv en Qa zijn vraag en aanbod. O zijn overheidsontvangsten; U zijn overheidsuitgaven; W is welvaartsverlies.

Reken tussentijds ongerond. Rond eurobedragen en percentages zo nodig op twee decimalen af. Elasticiteiten hebben geen eenheid. Hoeveelheden hebben wel een product- en zo nodig tijdseenheid.

### Grafieken en verklaringen

Gelijkwaardige, correct gelabelde grafieken zijn goed. Een andere kleur of arcering is geen fout. Een verklaring is goed wanneer de gebruikte gegevens en het economische gevolg logisch aan elkaar verbonden zijn. De bonusantwoorden zijn voorbeelden; hun beoordelingscriteria geven de vereiste inhoud aan.

<div class="small muted">Dit zijn nieuw geschreven oefenopgaven op basis van de door de gebruiker aangeleverde outlines v2. Het zijn geen overgenomen officiële examenvragen en de uitwerkingen zijn geen officieel correctievoorschrift.</div>
''')
page('3.1.1','Start en begeleide inoefening',''.join(answer(n) for n in range(1,5))+fig('3.1.1_ans_1','Opgave 4: A + t, Qt = 40 en de prijzen € 12 en € 8.'))
page('3.1.1','Zelfstandige oefening',answer(5)+fig('3.1.1_ans_2','Opgave 5: de belasting verlaagt Q van 40 naar 30. De twee prijzen liggen € 3 uit elkaar.')+answer(6))
page('3.1.1','Doeloefening',answer(7)+fig('3.1.1_ans_3','Opgave 7: kopers betalen € 10, verkopers ontvangen € 7; er worden 50 tassen verkocht.'))
page('3.1.1','Bonus en herhaling',answer(8)+criteria('Een goed antwoord behoudt dezelfde wig, noemt dezelfde marktuitkomst en laat de nieuwe geldstromen optellen tot de totale kopersbetaling.')+answer(9)+'''<div class="box"><b>Hulp bij herstel</b><br>Loopt opgave 9 vast? Herhaal de procentberekening en de indeling van prijselasticiteit uit §2.2.1 van Boek 2.</div>''')
page('3.1.2','Start en begeleide inoefening',''.join(answer(n) for n in range(10,14)))
page('3.1.2','Zelfstandige oefening',answer(14)+fig('3.1.2_ans_1','Opgave 14: O = € 160; W = € 40 per week.')+answer(15))
page('3.1.2','Doeloefening',answer(16)+fig('3.1.2_ans_2','Opgave 16: O is de rechthoek van € 150; de kleine driehoek W is € 15.'))
page('3.1.2','Bonus en herhaling',answer(17)+criteria('Het antwoord vergelijkt de vraagreactie vanaf dezelfde uitgangswaarden, verbindt dat met de aandelen in de belasting en benoemt de constant gehouden omstandigheden.')+answer(18))
page('3.1.3','Start en begeleide inoefening',''.join(answer(n) for n in range(19,23))+fig('3.1.3_ans_1','Opgave 22: Qsub = 80, Pc = € 14 en Pp = € 18.'))
page('3.1.3','Zelfstandige oefening',answer(23)+fig('3.1.3_ans_2','Opgave 23: de subsidie maakt Pc lager en Pp hoger bij dezelfde hoeveelheid van 70.')+answer(24))
page('3.1.3','Doeloefening',answer(25)+fig('3.1.3_ans_3','Opgave 25: U = € 210. W = € 15 markeert de extra transacties voorbij het vrije evenwicht.'))
page('3.1.3','Bonus en herhaling',answer(26)+criteria('Vergelijk de gelijke uitgaven, leg het verschil per extra verkoop uit en respecteer de gegeven onveranderde marginale kosten en marktdeelname bij de vaste steun.')+answer(27))
page('3.1.4','Start en begeleide inoefening',''.join(answer(n) for n in range(28,32))+fig('3.1.4_ans_1','Opgave 31: 80 gewenst, 40 aangeboden en verkocht; 40 tekort.'))
page('3.1.4','Zelfstandige oefening',answer(32)+fig('3.1.4_ans_2','Opgave 32: de gewenste aankoop is 70, maar er worden 40 spellen verkocht.')+answer(33))
page('3.1.4','Doeloefening',answer(34)+fig('3.1.4_ans_3','Opgave 34: 40 tenten worden verhuurd en 40 vragers blijven zonder tent.'))
page('3.1.4','Bonus en herhaling',answer(35)+criteria('Bereken alleen het surplus van kopers die daadwerkelijk kopen. Benoem de verschillende toewijzing en houd het eerlijkheidsoordeel apart.')+answer(36))
page('3.1.5','Start en begeleide inoefening',''.join(answer(n) for n in range(37,41))+fig('3.1.5_ans_1','Opgave 40: de overheid koopt 40 perenkratten voor € 14; U = € 560.'))
page('3.1.5','Zelfstandige oefening',answer(41)+fig('3.1.5_ans_2','Opgave 41: volledige opkoop geeft U = € 720; niet alle 80 kratten zijn overheidsaankopen.')+answer(42))
page('3.1.5','Doeloefening',answer(43)+fig('3.1.5_ans_3','Opgave 43, regeling A: 80 kratten productie, 40 particuliere aankopen en 40 overheidsaankopen.'))
page('3.1.5','Doeloefening (vervolg), bonus en herhaling',fig('3.1.5_ans_4','Opgave 43, regeling B: bij alleen een quotum van 40 bedraagt de prijs ook € 16, maar de totale productie is 40.')+answer(44)+criteria('Verwerp de gelijkstelling van budget en verlies; noem relevante ontbrekende informatie over gebruikswaarde en reële bijkomende kosten zonder een uitkomst te verzinnen.')+answer(45))
page('3.1.6','Methodekeuze',answer(46)+answer(47))
page('3.1.6','Doeloefening · plan A',answer(48,indices=[0,1,2,3])+fig('3.1.6_ans_1','Opgave 48, plan A: O = € 150 en W = € 15 per dag.'))
page('3.1.6','Doeloefening · plan B en conclusie',answer(48,indices=[4,5],continued=True)+fig('3.1.6_ans_2','Opgave 48, plan B: Qv = 70, Qa = 40, verkoop 40 en tekort 30. Deze tweede grafiek was niet verplicht.')+'''<div class="box"><b>Herstelgericht nakijken</b><br>Fout met de twee prijzen: herhaal §3.1.1. Budget verward met W: herhaal §3.1.2. Tekort of verkopen verkeerd: herhaal §3.1.4. Niet de hele berekening opnieuw memoriseren, maar het verkeerde onderscheid herstellen.</div>''')

# Keep a guided solution and its graphic on one explicit page.
for idx,n in sorted([(1,4),(9,22),(13,31),(17,40)],reverse=True):
    body=P[idx]['body'];marker=f'<div class="answer-block" id="ans{n}">';cut=body.index(marker)
    P.insert(idx+1,{'section':P[idx]['section'],'title':'Begeleide inoefening · uitwerking','body':body[cut:]})
    P[idx]['body']=body[:cut]
for old,new in [('1–9 | 2','1–9 | 2'),('10–18 | 6','10–18 | 7'),('19–27 | 10','19–27 | 11'),('28–36 | 14','28–36 | 16'),('37–45 | 18','37–45 | 21'),('46–48 | 22','46–48 | 26')]:
    P[0]['body']=P[0]['body'].replace(old,new)

def export():
    assert set(A)==set(E)
    (ROOT/'answers.json').write_text(json.dumps(A,ensure_ascii=False,indent=2))
    text='\n\n'.join('<!-- PAGE '+json.dumps({k:v for k,v in p.items() if k!='body'},ensure_ascii=False)+' -->\n\n'+p['body'] for p in P)
    (ROOT/'Antwoorden.md').write_text(text)
    (ROOT/'3.1 Overheidsingrijpen – antwoorden.md').write_text('\n\n<div class="page-break"></div>\n\n'.join(p['body'] for p in P))
    print('Answers:',len(A),'subanswers:',sum(map(len,A.values())),'designed pages:',len(P))
if __name__=='__main__':export()
