from author_common import *
section('4.3.6')
page('Gemengde opgaven',begin('Kies zelf de juiste aanpak',
'Je kunt informatie uit verschillende arbeidsmarktbronnen gebruiken. Je kunt zelfstandig een loon en hoeveelheid berekenen. Je kunt participatie, werkloosheid, productiviteit en beleid verbinden zonder verschillende grootheden te verwarren.',
'Een regio kan tegelijk een hogere participatie, meer vacatures en onveranderde werkgelegenheid hebben. Je kiest in deze paragraaf zelf welke telling, berekening of modelaanname nodig is. Er komt geen nieuwe theorie bij.')+
heading('Gemengde oefening')+
ex('Drie uitspraken controleren','Beoordeel de uitspraken met één berekening of een korte economische verklaring.',[
('Een bedrijf gebruikt 160 arbeidsuren van 8 mensen. De voltijdweek is 40 uur. “Er werken dus vier mensen.”',ans('Het bedrijf gebruikt 160 / 40 = <b>4 fte</b>, maar er werken <b>8 personen</b>.','Fte is de omvang van de arbeidsinzet, geen telling van mensen.')),
('In een gebied zijn 960 werkenden, 40 werklozen en 30 vacatures. Iedereen heeft één baan. “De werkloosheid is 1%.”',ans('Beroepsbevolking = 960 + 40 = <b>1.000 personen</b>; werkloosheid = 40 / 1.000 × 100% = <b>4%</b>.','De 30 vacatures mogen niet van de 40 werklozen worden afgetrokken.')),
('Een sector heeft hogere uurkosten maar lagere loonkosten per product. “Dat kan niet.”',ans('Dat kan wel als de productiviteit voldoende sterk stijgt. Je deelt uurkosten door productie per uur.','Het uurbedrag en het productbedrag hebben verschillende eenheden.'))])+
box('Werkwijze','Lees eerst over welke groep en periode de bron gaat. Noteer de eenheden. Kies dan pas de formule. Een bron met inwoners en een aparte sectorfunctie zijn niet automatisch één en dezelfde arbeidsmarkt.','summary'))
page('Rekenen en verklaren',heading('Gemengde oefening').replace('## Gemengde oefening','<div class="continuation">Gemengde oefening · vervolg</div>')+
ex('Een exporteur automatiseert','Een producent maakt eerst 6.000 onderdelen in 1.000 arbeidsuren. Na een nieuwe machine zijn er orders voor 7.560 onderdelen en maakt het bedrijf 7,2 onderdelen per uur. De volledige uurkosten gaan van € 24 naar € 25,20. Andere productiekosten zijn niet gegeven.',[
('Bereken de oude productiviteit, de nieuwe benodigde arbeidsuren en de verandering in uren.',ans('Oude productiviteit = 6.000 / 1.000 = <b>6 onderdelen per uur</b>. Nieuwe uren = 7.560 / 7,2 = <b>1.050 uur</b>. Verandering = 50 / 1.000 × 100% = <b>+5%</b>.','De productie groeit sterker dan de productiviteit.')),
('Bereken de oude en nieuwe loonkosten per onderdeel. Is daarmee bewezen dat de winst stijgt?',ans('Oud = 24 / 6 = <b>€ 4 per onderdeel</b>. Nieuw = 25,20 / 7,2 = <b>€ 3,50 per onderdeel</b>. Winststijging is niet bewezen: opbrengsten en andere kosten ontbreken.','Loonkosten per product zijn niet alle kosten en niet de totale winst.'))])+ 
ex('Een loonafspraak boven de markt','Lᵥ = 180 − 6w en Lₐ = −12 + 6w. L is het aantal personen met 20 uur per week; w is het uurloon in euro. Het model geldt voor € 2 ≤ w ≤ € 30. Er zijn geen vacatures of zoekproblemen. Een cao legt een loonvloer van € 18 vast. Bij de vraag verandert verder niets.',[
('Bereken het vrije evenwicht en de werkgelegenheid en loonsom bij de afspraak.',ans('180 − 6w = −12 + 6w → 192 = 12w → <b>w = € 16</b>, L = <b>84 personen</b>. Bij € 18: Lᵥ = 72; de werkgelegenheid is <b>72 personen</b>. Loonsom = 18 × 20 × 72 = <b>€ 25.920 per week</b>.','De afspraak ligt boven het vrije loon en bindt.')),
('Verandert de arbeidsvraaglijn door alleen deze loonvloer? Wat is het aanbodoverschot?',ans('Nee; het loon verandert de hoeveelheid langs de vraaglijn. Lₐ = −12 + 6 × 18 = <b>96</b>; overschot = 96 − 72 = <b>24 personen</b>.','Een loonregel en een verschuiving van de onderliggende arbeidsvraag zijn niet hetzelfde.'))]))
page('Bronnen bij de doeloefening',heading('Doeloefening')+
'''### Bronnen bij opgave 49 · Werk in Havenregio
Gebruik deze bronnen voor de vragen op de rechterpagina. **Bron A is een regiotelling. Bron B is een apart vereenvoudigd sectormodel.** Bron C is een voorstel, geen waargenomen resultaat.

'''+source('Bron A · Inwoners van 15 tot 75 jaar',table(['Groep','Personen'],[['Betaald werk','12.600'],['Geen betaald werk, recent gezocht en direct beschikbaar','1.400'],['Niet-beroepsbevolking','6.000']]))+
source('Bron B · Verpakkingssector','Oorspronkelijk: Lᵥ = 240 − 10w; Lₐ = −40 + 10w. Door extra buitenlandse orders wordt de vraag Lᵥ = 280 − 10w. Het aanbod verandert niet.<br>L is het aantal personen met ieder 20 uur per week; w is het uurloon in euro. Gebruik € 4 ≤ w ≤ € 24. Werkgevers concurreren, het loon kan vrij aanpassen en alle gevraagde plaatsen worden gevuld zonder vacatures of zoekproblemen.')+
fig('mixed_base','Markeer in deze basisgrafiek het oude en nieuwe evenwicht. De verschuiving van de vraaglijn is al gegeven.')+
source('Bron C · Scholingsvoorstel','In een afzonderlijk bedrijf zouden de volledige uurkosten stijgen van € 24 naar € 25,20. De productiviteit zou stijgen van 8 naar 8,8 producten per uur. De omvang van de toekomstige orders en opleidingskosten zijn nog onbekend. Een woordvoerder zegt: “Dit voorstel levert gegarandeerd meer banen op.”'))
page('Doeloefening vragen',ex('Werk in Havenregio','Gebruik uitsluitend de relevante bronnen op de linkerpagina. Geef bij elke berekening de eenheid. Schrijf verklaringen in volledige zinnen.',[
('Bereken met bron A de beroepsbevolking, bruto-participatie en het werkloosheidspercentage.',ans('Bevolking = 12.600 + 1.400 + 6.000 = <b>20.000 personen</b>. Beroepsbevolking = <b>14.000 personen</b>. Bruto = 14.000 / 20.000 × 100% = <b>70%</b>. Werkloosheid = 1.400 / 14.000 × 100% = <b>10%</b>.','Participatie en werkloosheid hebben verschillende noemers.')),
('Bereken met bron B zelfstandig het oorspronkelijke evenwichtsloon en de werkgelegenheid.',ans('240 − 10w = −40 + 10w → 280 = 20w → <b>w = € 14</b>. L = 240 − 10 × 14 = <b>100 personen</b>.','Bij het evenwicht zijn arbeidsvraag en arbeidsaanbod gelijk.')),
('Bereken het nieuwe evenwicht na de extra orders. Markeer beide evenwichten in de basisgrafiek.',ans('280 − 10w = −40 + 10w → 320 = 20w → <b>w = € 16</b>. L = 280 − 10 × 16 = <b>120 personen</b>. E₀ = (100;14); E₁ = (120;16).','Extra orders verschuiven arbeidsvraag naar rechts; de nieuwe werkgelegenheid is hoger.')),
('Een leerling zegt: “De loonstijging verschuift de arbeidsvraag naar rechts.” Verbeter dit met bron B en benoem wat langs de aanbodlijn gebeurt.',ans('De <b>extra exportorders</b> verschuiven de arbeidsvraag. Het hogere loon is een uitkomst van de nieuwe verhouding. Langs de gelijk gebleven aanbodlijn stijgt de aangeboden hoeveelheid van 100 naar 120 personen.','Oorzaak van een lijnverschuiving en beweging langs een andere lijn zijn verschillende onderdelen van de aanpassing.')),
('Bereken met bron C de loonkosten per product vóór en na het voorstel en de procentuele verandering.',ans('Oud = 24 / 8 = <b>€ 3 per product</b>. Nieuw = 25,20 / 8,8 = <b>€ 2,863636… ≈ € 2,86 per product</b>. Verandering = (2,863636… − 3) / 3 × 100% ≈ <b>−4,55%</b>.','Reken met onafgeronde bedragen tot het eindantwoord.')),
('Beoordeel de garantie van meer banen in bron C. Noem één ondersteunde uitkomst en één ontbrekend gegeven dat de werkgelegenheid kan beïnvloeden.',ans('Onder de veronderstelde veranderingen dalen de loonkosten per product. Meer banen zijn niet gegarandeerd: de toekomstige productie/orders ontbreken. Bij dezelfde productie zou de hogere productiviteit juist minder arbeidsuren vragen.','Een dalend bedrag per product bepaalt niet vanzelf hoeveel producten worden gemaakt of hoeveel mensen werken.'))],points=[3,2,2,2,3,2],answer_fig='mixed_answer')+
box('Controle vóór inleveren','Heb je de twee noemers onderscheiden? Hebben je lonen en hoeveelheden eenheden? Is je beleidsconclusie niet sterker dan de informatie uit de bron?','summary'))
page('Afsluiten met een modelkritiek',heading('Denkertje / Bonusopgave')+
ex('Hetzelfde bericht, verschillende verklaringen','Een bericht luidt: “Het gemiddelde uurloon is hoger, de werkloosheid is lager en werkgevers melden meer vacatures.” Er staan geen aanvullende cijfers of oorzaken bij.',[
('Geef twee verschillende, economisch mogelijke verklaringen voor dit bericht. Geef vervolgens aan welke informatie je nodig hebt om ertussen te kiezen.',
'Een mogelijkheid is groei van de arbeidsvraag door extra orders: meer aanstellingen verlagen de werkloosheid en concurrentie om personeel geeft opwaartse loondruk. Een andere mogelijkheid is een combinatie van loonafspraken en mensen die stoppen met zoeken; het werkloosheidscijfer kan dan dalen zonder extra banen, terwijl bestaande vacatures door mismatch openblijven. Nodig zijn bijvoorbeeld werkenden, beroepsbevolking, gewerkte uren, nieuwe orders en aard van vacatures.<br><b>Beoordelingscriteria:</b> geeft twee intern mogelijke mechanismen; trekt geen noodzakelijke causaliteit uit het bericht; noemt gegevens die de verklaringen onderscheiden.')])+
'''### Dit kun je nu zelf controleren
Kies een eerder gemaakte fout en verbeter niet alleen het getal, maar ook de uitleg. Gebruik de terugwijzing die bij je fout past.

'''+table(['Een fout die je herkent','Kijk terug bij'],[['Personen als uren gebruiken','§4.3.1 · arbeid meten'],['Werklozen buiten bruto-participatie laten','§4.3.2 · groepen en deelname'],['Vacatures aftrekken van werklozen','§4.3.3 · tellen versus model'],['Het minimum altijd als feitelijk loon gebruiken','§4.3.4 · bindendheid'],['Loon- en productiviteitsgroei gewoon aftrekken','§4.3.5 · kosten per product']])+
box('Van uitkomst naar betekenis','De berekening beantwoordt een afgebakende vraag. Leg daarna uit wie de uitkomst raakt, welke omstandigheden gelijk blijven en wat je met de bron niet kunt vaststellen.','summary'))
