"""Render editable Markdown manuscripts to searchable, vector-figure PDFs.
python make_assets.py && python build.py
No authoring source is silently regenerated by this renderer.
"""
from pathlib import Path
import re,json,base64
from markdown_it import MarkdownIt
from bs4 import BeautifulSoup
from weasyprint import HTML
import fitz
ROOT=Path(__file__).resolve().parent;OUT=ROOT/'output';OUT.mkdir(exist_ok=True)
md=MarkdownIt('commonmark',{'html':True}).enable('table')
CSS=(ROOT/'print.css').read_text()
def render_md(body):
    pat=re.compile(r'(<div\b[^>]*>)([\s\S]*?)(</div>)')
    def f(m):
        inn=m.group(2)
        if '\n\n' in inn or re.search(r'^\|',inn,re.M):return m.group(1)+'\n'+md.render(inn.strip())+'\n'+m.group(3)
        return m.group(0)
    body=re.sub(r'(</(?:div|a)>)[ \t]*\n(?=#)',r'\1\n\n',body)
    return md.render(pat.sub(f,body))
def page_chunks(path):
    chunks=re.split(r'<!-- PAGE (.*?) -->',path.read_text(),flags=re.S)
    for i in range(1,len(chunks),2):
        p=json.loads(chunks[i]);p['body']=chunks[i+1].strip();yield p

def build(pages,stem,title,kind='student'):
    chunks=[]
    for n,p in enumerate(pages,1):
        head='' if n==1 or re.search(r'^# ',p['body'],re.M) or p['body'].lstrip().startswith('## ') else f'<div class="page-title">{p["section"]} · {p["title"]}</div>'
        chunks.append(f'<section class="page {kind}" data-designed-page="{n}">'+head+render_md(p['body'])+'</section>')
    soup=BeautifulSoup('\n'.join(chunks),'html.parser')
    for img in soup.find_all('img'):
        f=ROOT/img['src']
        if not f.exists():raise FileNotFoundError(f)
        img['src']='data:'+('image/svg+xml' if f.suffix=='.svg' else 'image/png')+';base64,'+base64.b64encode(f.read_bytes()).decode()
    extra='' if kind=='student' else ('html{font-size:10.8pt;line-height:1.36;} .formula{font-size:10pt;}' if kind=='answer' else 'html{font-size:10.7pt;}')
    html='<!doctype html><html lang="nl"><head><meta charset="utf-8"><title>'+title+'</title><style>'+CSS+extra+'</style></head><body>'+str(soup)+'</body></html>'
    (OUT/(stem+'.html')).write_text(html)
    doc=HTML(string=html,base_url=str(ROOT)).render()
    doc.write_pdf(OUT/(stem+'.pdf'))
    mapping=[]
    for n,pg in enumerate(doc.pages,1):
        nums=set(); outside=[]
        for el in pg._page_box.descendants():
            e=getattr(el,'element',None)
            if e is not None and e.get('data-designed-page'):nums.add(int(e.get('data-designed-page')))
        mapping.append({'pdf_page':n,'designed_pages':sorted(nums)})
    (ROOT/'QA'/(stem+'_page_map.json')).write_text(json.dumps(mapping,indent=2))
    with fitz.open(OUT/(stem+'.pdf')) as pdf:
        if kind=='student':
            names=[('Inhoud · Arbeidsmarkt',1),('4.3.1 Arbeidsvraag en arbeidsproductiviteit',2),('4.3.2 Arbeidsaanbod, participatie en evenwicht',12),('4.3.3 Werkloosheid en veranderingen',20),('4.3.4 Minimumloon',29),('4.3.5 Vakbonden, cao en arbeidsmarktbeleid',37),('4.3.6 Gemengde opgaven: arbeidsmarkt',44),('Hoofdstukoverzicht',49),('Begrippenlijst',50)]
            pdf.set_toc([[1,t,n] for t,n in names])
        for pg in pdf:
            for link in pg.get_links():
                if link.get('nameddest') and link.get('page',-1)>=0:
                    pg.update_link({'xref':link['xref'],'kind':fitz.LINK_GOTO,'from':link['from'],'page':link['page'],'to':fitz.Point(0,0),'zoom':0})
        temp=OUT/(stem+'.nav.pdf');pdf.save(temp,garbage=4,deflate=True)
    temp.replace(OUT/(stem+'.pdf'))
    overflow=[m for m in mapping if m['designed_pages']!=[m['pdf_page']]]
    print(stem,len(doc.pages),'pages;',len(pages),'planned sections')
    if kind=='student' and (overflow or len(doc.pages)>50):
        print('PAGE DRIFT:',overflow);return False
    return True
if __name__=='__main__':
    order=json.loads((ROOT/'chapter-order.json').read_text())
    pages=[p for f in order for p in page_chunks(ROOT/f)]
    (ROOT/'4.3 Arbeidsmarkt – hoofdstuk.md').write_text('\n\n'.join((ROOT/f).read_text() for f in order))
    ok=build(pages,'Boek_4_H3_Arbeidsmarkt','Boek 4 · Hoofdstuk 3 · Arbeidsmarkt')
    for f,stem,title,kind in [('Antwoorden.md','Boek_4_H3_Antwoorden','Antwoorden · Arbeidsmarkt','answer'),('Docenteninformatie.md','Boek_4_H3_Docenteninformatie','Docenteninformatie · Arbeidsmarkt','teacher')]:
        if (ROOT/f).exists():build(list(page_chunks(ROOT/f)),stem,title,kind)
    if not ok:raise SystemExit(2)
