from author_common import *
def author():
 section('4.2.7')
 page('Gemengde opgaven',begin('Welke rekening hoort bij deze markt?',
 'Je kunt uit bronnen het passende model kiezen. Je kunt marktgedrag verbinden met surplus en gevolgen voor derden. Je kunt een beleidsconclusie onderbouwen én begrenzen.',
 'De volgende gevallen gebruiken alleen eerder behandelde technieken. Je moet nu zelf bepalen welke rekening bij de bron past. Een hogere winst, meer deelnemers of een grote overheidsontvangst is nog geen eindconclusie.')+heading('Gemengde oefening')+ex('Eerst de juiste vraag',
 'A: één aanbieder verkoopt minder om meer winst te maken; er zijn geen externe effecten. B: veel aanbieders veroorzaken per product niet-vergoede schade bij buren. C: twee herkenbare klantgroepen betalen verschillende prijzen voor dezelfde dienst.',[
 ('Welke vergelijking heb je bij A nodig om welvaartsverlies te bepalen?','Vergelijk de monopolie-uitkomst met een efficiënte uitkomst bij dezelfde vraag en kosten. Bereken of identificeer beide TS-waarden en het verloren surplus; een prijsverschil alleen is onvoldoende.'),
 ('Welke post mag bij B niet ontbreken? Welke bekende techniek helpt als een heffing wordt ingevoerd?','De totale externe schade moet van de maatschappelijke rekening af. De bekende heffingswig Pc = Pp + t geeft de nieuwe hoeveelheid en prijzen; daarna tel je CS, PS en overheid op en trek je schade en eventuele uitvoering af.'),
 ('Wat controleer je bij C voordat je afzonderlijke prijzen als haalbaar behandelt?','Of de aanbieder marktmacht heeft, de groepen kan herkennen en doorverkoop of overstappen naar het goedkope tarief kan voorkomen. Bij aparte optimalisatie moeten de kostenvoorwaarden ook passend zijn.')])+'''
### Een bruikbaar antwoord laat de keuze zien
Schrijf bijvoorbeeld: **“Deze bron gaat over niet-vergoede schade aan buren. Daarom vergelijk ik niet alleen CS + PS, maar trek ik ook de totale externe kosten af.”**

Noem daarna de berekening en de conclusie. Het is niet nodig om alle formules uit het hoofdstuk op elke bron los te laten.
'''+box('Werk met dezelfde periode','Vergelijk dagbedragen met dagbedragen en maandbedragen met maandbedragen. De twee cases in de doeloefening zijn afzonderlijke markten; hun bedragen worden niet bij elkaar opgeteld.','small'))
 page('Cijfers en verdeling combineren',ex('Het centrum voor bezoekers',
 'Een aanbieder met marktmacht kan twee klantgroepen betrouwbaar scheiden. Dezelfde dienst kost voor iedere bezoeker € 2 aan variabele kosten. Gezamenlijke vaste kosten: € 60 per week. De tabel geeft twee uitvoerbare prijsplannen. Andere omstandigheden blijven gelijk en er zijn geen externe effecten.',[
 ('Bereken bij ieder plan de totale omzet en winst.','Eén prijs: Q = 30 + 10 = 40; TO = 10 × 40 = € 400; TK = 60 + 2 × 40 = € 140; winst = € 260. Groepsprijzen: Q = 25 + 15 = 40; TO = 12 × 25 + 8 × 15 = € 420; TK = € 140; winst = € 280 per week.'),
 ('Bereken met het gegeven CS voor beide plannen TS.','PS één prijs = 400 − 80 = € 320; TS = 200 + 320 = € 520. PS groepsprijzen = 420 − 80 = € 340; TS = 170 + 340 = € 510. TS daalt € 10 per week.'),
 ('Beoordeel: “De totale afzet is gelijk en de winst stijgt, dus er kan geen nadeel zijn.”','Onjuist. De verdeling van verkopen tussen groepen verandert. A betaalt meer en koopt minder; B betaalt minder en koopt meer. Het totale CS daalt € 30, terwijl PS € 20 stijgt; daardoor daalt TS € 10.'),
 ('Wat zou veranderen als de goedkope kaartjes zonder controle konden worden doorverkocht?','Kopers uit de dure groep kunnen dan goedkope kaartjes overnemen. De opgegeven gescheiden groepsprijzen en verkopen blijven niet vanzelf uitvoerbaar.')])+'''
| Gegeven | Eén prijs | Groepsprijzen |
|---|---:|---:|
| Prijs A | € 10 | € 12 |
| Aantal A | 30 | 25 |
| Prijs B | € 10 | € 8 |
| Aantal B | 10 | 15 |
| Totaal CS (€ per week) | 200 | 170 |
'''+box('Geen nieuw rekenmodel','De prijs- en afzetkeuzes zijn in deze bron gegeven. Je vergelijkt hun gevolgen. Je hoeft geen ontbrekende vraagfunctie te reconstrueren of de gezamenlijke prijs opnieuw te optimaliseren.','small')+'''
### Onderbouw per groep
Een verandering van het totale consumentensurplus zegt nog niet dat elk individu hetzelfde ervaart. Begin je uitleg met de prijs- en afzetverandering van A en B afzonderlijk. Maak daarna pas de stap naar totalen.
''')
 page('Een extern voordeel en uitvoeringskosten',ex('De gezamenlijke cursus',
 'Een concurrerende cursusmarkt heeft vraag Pc = 40 − Q en aanbod Pp = Q. Q is deelnemers per maand, met 0 ≤ Q ≤ 40; prijzen zijn euro per deelnemer. Andere buurtbewoners hebben € 8 bijkomend voordeel per deelnemer, zonder ervoor te betalen. Aanbieders krijgen € 8 subsidie per gebruikte plaats. De uitvoering verbruikt € 10 aan middelen per maand. Er zijn geen andere maatschappelijke posten.',[
 ('Bereken de oorspronkelijke markt en de uitkomst met subsidie, inclusief beide prijzen.','Zonder subsidie: 40 − Q = Q → Q₀ = 20 en P₀ = € 20. Met subsidie: Q = 40 − Q + 8 → Q₁ = 24. Pc = € 16 en Pp = € 24.'),
 ('Bereken de overheidsuitgaven en het totale externe voordeel na de subsidie.','Uitgaven = 8 × 24 = € 192 per maand. Externe baten = 8 × 24 = € 192 per maand. Hun bedragen zijn gelijk door de gekozen gegevens; het blijven verschillende posten.'),
 ('CS en PS zijn zonder subsidie elk € 200 en met subsidie elk € 288. Bereken de maatschappelijke verandering, inclusief uitvoering.','Voor: 200 + 200 + 8 × 20 = € 560. Na: 288 + 288 − 192 + 192 − 10 = € 566. De nettoverbetering is € 6 per maand.'),
 ('Waarom kun je niet gewoon de stijging van CS + PS als welvaartswinst rapporteren?','De stijging van CS + PS bevat de ontvangen subsidie. Overheidsuitgaven, externe baten en echte uitvoeringskosten moeten ook worden meegenomen. Anders wordt een overdracht voor echte extra welvaart aangezien.')],answer_fig='425_mixed57')+fig('425_mixed','Gebruik de al bekende private vraag, maatschappelijke baten en kosten om de hoeveelheden te controleren.')+box('Van berekening naar oordeel','Benoem het criterium en vergelijk de volledige maatschappelijke rekening vóór en na. Geef vervolgens aan of je conclusie gevoelig kan zijn voor veranderende uitvoeringskosten of een overschat extern voordeel. Een begrotingsbedrag alleen is geen welvaartsoordeel.','small'))
 page('Bronnen bij de doeloefening',heading('Doeloefening')+source('Bron A · Studio Solo',
 'Eén aanbieder verhuurt de hele afgebakende markt voor studiosessies. Vraag: P = 70 − Q. TK = 100 + 10Q + 0,5Q² en MK = 10 + Q. Q is sessies per week en P euro per sessie. Capaciteit: 50 sessies. Constante kosten blijven in deze week gelijk. Er zijn geen externe effecten. De efficiënte vergelijkingsuitkomst bij dezelfde vraag en kosten is Qe = 30, Pe = € 40 en TSe = € 900 per week.')+fig('427_A','Bron A: vraag, MO en MK voor dezelfde markt. De monopolie-uitkomst is nog niet gemarkeerd.')+source('Bron B · Reiniging bij woningen',
 'Veel aanbieders leveren dezelfde dienst. Vraag: Pc = 60 − Q; aanbod: Pp = Q. Q is diensten per dag; prijzen zijn euro per dienst. Iedere dienst veroorzaakt € 20 niet-vergoede schade aan omwonenden. Producenten gaan € 20 per dienst afdragen. Na de heffing zijn CS en PS elk € 200 per dag. Zonder ingrijpen is het maatschappelijk surplus € 300 per dag. Geen uitvoeringskosten of andere externe effecten.')+fig('427_B','Bron B: private en maatschappelijke kosten. Het gaat hier om een andere markt en een andere periode dan in bron A.'))
 page('Doel: zelf het juiste model kiezen',ex('Twee markten, twee oorzaken',
 'Gebruik de bronnen op de linkerpagina. Onderbouw berekeningen met eenheden en conclusies met brongegevens.',[
 ('Bepaal voor Studio Solo de winstmaximale hoeveelheid en verkoopprijs. Bereken ook de winst.','MO = 70 − 2Q. 70 − 2Q = 10 + Q geeft Qm = 20 sessies per week. MO daalt door MK en 20 past binnen 50. Pm = € 50. TO = 50 × 20 = € 1.000; TK = 100 + 10 × 20 + 0,5 × 20² = € 500; winst = € 500 per week.'),
 ('Bereken CS, PS en TS bij Solo en vergelijk met het gegeven TSe. Arceer het welvaartsverlies in figuur A.','CS = ½ × 20 × (70 − 50) = € 200. MK(20) = € 30; PS = 20 × (50 − 30) + ½ × 20 × (30 − 10) = € 600. TS = € 800. Welvaartsverlies = 900 − 800 = € 100 per week. Het is de driehoek tussen vraag en MK van Q = 20 tot Q = 30, basis 10 en hoogte 20.'),
 ('Bereken in bron B de belaste hoeveelheid, Pc, Pp en de heffingsopbrengst.','Pc = Pp + 20: 60 − Q = Q + 20 → Q = 20 diensten per dag. Pc = € 40; Pp = € 20. Heffingsopbrengst = 20 × 20 = € 400 per dag.'),
 ('Bereken met bron B het maatschappelijk surplus na de heffing en de verandering ten opzichte van de beginsituatie.','Totale externe schade na heffing = 20 × 20 = € 400 per dag. Maatschappelijk surplus = 200 + 200 + 400 − 400 = € 400. Verbetering = 400 − 300 = € 100 per dag.'),
 ('Leg uit waarom minder verkopen bij Solo welvaartsverlies geeft, maar minder diensten in bron B juist verbetering kan geven.','Bij Solo zijn er geen externe effecten; tussen Qm en Qe is betalingsbereidheid groter dan MK en verdwijnen voordelige transacties. Bij B veroorzaken sommige oorspronkelijke diensten meer maatschappelijke kosten dan baten door schade aan derden. Het verminderen van die diensten vergroot het maatschappelijke saldo.'),
 ('Beoordeel: “Een heffing van € 20 is dus ook vanzelf de beste oplossing voor Studio Solo.”','Dat volgt niet. De heffing van € 20 in B past bij de daar gegeven externe schade en concurrentie. Solo heeft juist marktmacht en geen genoemde externe schade. Zonder analyse van dat probleem en de beleidsreactie is dezelfde maatregel niet gerechtvaardigd.')],points=[3,4,3,2,2,2],answer_fig=['427_answerA','427_answerB'])+box('Controleer vóór je afsluit','Is PS onderscheiden van winst? Is de prijs op de juiste lijn afgelezen? Zijn schade en overheidsontvangst allebei meegenomen? Gaat je conclusie alleen over de markt waarvoor je hebt gerekend?','small')+'''
### Schrijf geen grotere conclusie dan je bewijs
Een berekende verbetering in bron B is geen bewijs dat elke omwonende schadeloos is gesteld. Het welvaartsverlies in A is geen bewijs dat de hoogste mogelijke afzet altijd gewenst is. Je antwoord moet bij vraag, kosten, derden en de periode uit de bron blijven.
''')
 page('De belangrijkste denkfouten herstellen',heading('Extra gemengde oefening')+ex('Drie overtuigend klinkende uitspraken',
 'Beoordeel elke uitspraak. Geef niet alleen “juist” of “onjuist”, maar herstel de redenering.',[
 ('“Bij twee klantgroepen moet je voor elke groep opnieuw de totale huur aftrekken.”','Onjuist als het om één gezamenlijke huur gaat. Tel de totale omzet en afzet samen, bereken de totale variabele kosten en trek de gezamenlijke huur eenmaal af. Alleen werkelijk aparte kosten worden apart meegeteld.'),
 ('“Een producent met een dalende vraaglijn heeft altijd een monopolie.”','Onjuist. Ook onder monopolistische concurrentie kan een onderneming een dalende eigen vraag hebben. De marktvorm vereist broninformatie over aanbieders, productverschillen en toetreding.'),
 ('“Bij een subsidie is het externe voordeel gelijk aan wat de overheid uitgeeft.”','Onjuist als algemene regel. De subsidie volgt uit het tarief en de gebruikte hoeveelheid; externe baten volgen uit de werkelijke voordelen voor derden. Soms zijn de bedragen in een oefencase gelijk, maar het zijn verschillende posten.')])+heading('Herhaling / Herhaling en interleaving')+ex('Dezelfde techniek in twee vormen',
 'A: voor één onderneming geldt P = 30 − 0,5q en MK = € 10, met capaciteit 30. B: op een markt betalen kopers € 18, ontvangen producenten € 14 en worden 50 stuks verkocht. Alle bedragen bij B gelden per week.',[
 ('Bereken voor A de winstmaximale q en verkoopprijs.','MO = 30 − q. MO = 10 geeft q = 20, binnen de capaciteit. P = 30 − 0,5 × 20 = € 20 per eenheid. De hoeveelheid komt uit MO/MK, de prijs uit de vraag.'),
 ('Bereken voor B de heffing per stuk en de overheidsontvangst.','t = Pc − Pp = 18 − 14 = € 4 per stuk. Ontvangst = 4 × 50 = € 200 per week.'),
 ('Welke extra informatie is nodig om in B een maatschappelijke welvaartsverandering vast te stellen?','Een vergelijkbare beginsituatie en de relevante CS-, PS- en externe-effectposten, plus eventuele echte uitvoeringskosten. Alleen de wig en de overheidsontvangst bepalen de welvaartsverandering niet.')])+box('Je hoofdstuk in één zin','Kies het juiste model, tel alle relevante partijen mee en onderscheid een betaling van een echte verandering in kosten of baten.'))
